spring.application.name=pf_sistema_gestion_roles

spring.datasource.url=jdbc:postgresql://ep-empty-cell-aqirkpoh-pooler.c-8.us-east-1.aws.neon.tech/sistema_gr?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_q9nBcMVejg3z
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret = mysecretkey1234567890

cloudinary.cloud_name=dzebcxlzg
cloudinary.api_key=468755445586274
cloudinary.api_secret=BrFzn5yGJPw8cLTknKC5lW8Lil8

spring.devtools.restart.enabled=false
